# Generated by Django 3.2.3 on 2021-06-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210618_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.FloatField(max_length=25, null=True),
        ),
    ]
