# Generated by Django 3.2.3 on 2021-07-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
