# Generated by Django 3.2.3 on 2021-07-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210708_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.FloatField(max_length=25, null=True),
        ),
    ]
